### ISSUE TITLE
Support for ES6/Typescript

### ISSUE THREAD

**Issue by imduchy** [wigy/knex-dump#9]
Would it be possible to implement support for ES6/Typescript?

```
$ knex-dump --knexfile ./knexfile.ts --file dump.json dump
/Users/jakubduchon/Source/xxxxxx/knexfile.ts:1
import dotenv from 'dotenv'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/jakubduchon/Source/xxxxxx/node_modules/knex-dump/bin/cli.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
error Command failed with exit code 1.
```

I'll be happy to submit a PR, but I'm unsure how to support ES6 module within the ES5 library.

**Comment by eddiewang** [comment]
would love to see typescript support as well
